const handler = {
  async fetch() {
    const html: BodyInit = `<!DOCTYPE html>
          <body>
            <h1>Hello World!!!</h1>
            <p>This markup was generated by a Cloudflare Worker.</p>
          </body>`;

    const res = new Response(html, {
      headers: {
        'content-type': 'text/html;charset=UTF-8',
      },
    });

    return res;
  },
};

export default handler;
